### ISSUE TITLE
link gathering breaks on URLs that use some relative paths not based on host

### ISSUE THREAD

**Issue by joenorton** [joenorton/rubyretriever#14]
example:
on target http://abc.university.edu/~yoda/index/
where there are relative links like so: 'projects/files/'

then those relatives url's will get accidentally paired with the host and end up like such.
http://abc.university.edu/projects/files/

Is it better behavior for the scraper to assume 'append onto host'
a) http://abc.university.edu/projects/files/
or to assume 'append onto current url'
b) http://abc.university.edu/~yoda/index/projects/files/

**Comment by nofxx** [comment]
Use the leading slash to decide:

    projects/files   -> foo.com/bar/projects/files

    /projects/files  ->  foo.com/projects/files

  
Thank you for this gem man! The best ruby crawler there is.

**Comment by joenorton** [comment]
Fixed in 1.4.0
