### ISSUE TITLE
reject named anchors from sitemap crawl

### ISSUE THREAD

**Issue by lfender6445** [joenorton/rubyretriever#21]
bootstrap css framework requires the use of named anchors to get accordion widgets playing nicely with targets 

i noticed these are being collected by the sitemap when they do not represent valid urls for sitemaps

```
http://www.example.com/#collapseFive
```

see http://getbootstrap.com/2.3.2/javascript.html for more examples. perhaps we should filter them out or add them in as some sort of exclusion rule?

**Comment by joenorton** [comment]
Just fixed as of gem version 1.4.2.
